/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Starter from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace EligibilityInquiry {
    export interface Options {
        environment?: core.Supplier<environments.StarterEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class EligibilityInquiry {
    constructor(protected readonly _options: EligibilityInquiry.Options) {}

    /**
     * @param {Starter.EligibilityInquiryRequest} request
     * @param {EligibilityInquiry.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Starter.BadRequestError}
     * @throws {@link Starter.UnauthorizedError}
     * @throws {@link Starter.NotFoundError}
     * @throws {@link Starter.ContentTooLargeError}
     * @throws {@link Starter.InternalServerError}
     * @throws {@link Starter.ServiceUnavailableError}
     *
     * @example
     *     await client.eligibilityInquiry.medicareObProcessMain({
     *         Detail: {
     *             ResponsibleReportingEntity: "ResponsibleReportingEntity",
     *             Subscriber: {
     *                 Birthdate: "2024-01-15T09:30:00Z",
     *                 FirstName: "FirstName",
     *                 Gender: "M",
     *                 LastName: "LastName",
     *                 MedicareIDMember’s Medicare ID (HICN or MBI): "MedicareIDMember\u2019s Medicare ID (HICN or MBI)"
     *             }
     *         },
     *         Header: {}
     *     })
     */
    public async medicareObProcessMain(
        request: Starter.EligibilityInquiryRequest,
        requestOptions?: EligibilityInquiry.RequestOptions,
    ): Promise<unknown> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.StarterEnvironment.Default,
                "EligibilityInquiry",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "startersdk",
                "X-Fern-SDK-Version": "0.0.8",
                "User-Agent": "startersdk/0.0.8",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Starter.BadRequestError(_response.error.body as string);
                case 401:
                    throw new Starter.UnauthorizedError(_response.error.body as string);
                case 404:
                    throw new Starter.NotFoundError(_response.error.body as string);
                case 413:
                    throw new Starter.ContentTooLargeError(_response.error.body as string);
                case 500:
                    throw new Starter.InternalServerError(_response.error.body as string);
                case 503:
                    throw new Starter.ServiceUnavailableError(_response.error.body as string);
                default:
                    throw new errors.StarterError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StarterError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.StarterTimeoutError("Timeout exceeded when calling POST /EligibilityInquiry.");
            case "unknown":
                throw new errors.StarterError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-Key": apiKeyValue };
    }
}
