/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../../../index";

export interface EligibilityInquiryRequestDetailSubscriber {
    Birthdate: string;
    FirstName: string;
    Gender: Starter.EligibilityInquiryRequestDetailSubscriberGender;
    LastName: string;
    /**
     * Member’s Medicare ID
     * (HICN or MBI)
     */
    "MedicareIDMember’s Medicare ID (HICN or MBI)": string;
}
