/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EligibilityInquiryRequestDetailSubscriberGender = "M" | "F";
export const EligibilityInquiryRequestDetailSubscriberGender = {
    M: "M",
    F: "F",
} as const;
