/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../../../index";

export type EligibilityInquiryRequestDetailReference = string | Starter.EligibilityInquiryRequestDetailReferenceOne;
