/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../../../index";

export interface EligibilityInquiryRequestMeta {
    ReceivedDateTime?: string;
    Settings?: Starter.EligibilityInquiryRequestMetaSettings;
    Tags?: string[];
    id?: string;
    source?: string;
}
