/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../../../index";

export interface EligibilityInquiryRequestDetail {
    Reference?: Starter.EligibilityInquiryRequestDetailReference;
    /**
     * 9-digit Responsible
     * Reporting Entity (RRE)
     * number assigned by
     * COB.
     * The RRE number must
     * contain 9 digits.
     * Populate leading
     * positions with zeros.
     */
    ResponsibleReportingEntity: string;
    Subscriber: Starter.EligibilityInquiryRequestDetailSubscriber;
}
