/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EligibilityResponseResponseDetailSubscriberGender = "M" | "F";
export const EligibilityResponseResponseDetailSubscriberGender = {
    M: "M",
    F: "F",
} as const;
