/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../index";

export interface EligibilityResponseResponseDetailSubscriber {
    Birthdate: string;
    FirstName: string;
    Gender: Starter.EligibilityResponseResponseDetailSubscriberGender;
    LastName: string;
    /**
     * Member’s Medicare ID
     * (HICN or MBI)
     */
    MedicareID: string;
}
