/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../index";

export interface EligibilityResponseResponseDetail {
    /**
     * The number ‘9’ plus the
     * RRE number. The RRE
     * number must contain 9
     * digits. Populate leading
     * positions with zeros.
     */
    OriginatingCompanyID?: number;
    PlanEligibilitys?: Starter.EligibilityResponseResponseDetailPlanEligibilitysItem[];
    References?: Starter.EligibilityResponseResponseDetailReferencesItem[];
    RejectionReason?: Starter.EligibilityResponseResponseDetailRejectionReason;
    /**
     * 9-digit Responsible
     * Reporting Entity (RRE)
     * number assigned by
     * COB.
     * The RRE number must
     * contain 9 digits.
     * Populate leading
     * positions with zeros.
     */
    ResponsibleReportingEntity: string;
    Subscriber: Starter.EligibilityResponseResponseDetailSubscriber;
}
