/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EligibilityResponseResponseDetailRejectionReason =
    | "Subscriber or Insured not found"
    | "Duplicate Subscriber or Insured ID";
export const EligibilityResponseResponseDetailRejectionReason = {
    SubscriberOrInsuredNotFound: "Subscriber or Insured not found",
    DuplicateSubscriberOrInsuredId: "Duplicate Subscriber or Insured ID",
} as const;
