/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EligibilityResponseResponseDetailPlanEligibilitysItemPartC {
    ContractNumber?: string;
    PBPNumber?: string;
}
