/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../index";

export interface EligibilityResponseResponseDetailPlanEligibilitysItem {
    EndDate?: string;
    MedicarePart?: Starter.EligibilityResponseResponseDetailPlanEligibilitysItemMedicarePart;
    PartC?: Starter.EligibilityResponseResponseDetailPlanEligibilitysItemPartC;
    StartDate?: string;
}
