/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../index";

export interface EligibilityResponseResponseMeta {
    ReceivedDateTime?: string;
    Settings?: Starter.EligibilityResponseResponseMetaSettings;
    Tags?: string[];
    id?: string;
    source?: string;
}
