/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../index";

export interface EligibilityResponseResponse {
    Detail: Starter.EligibilityResponseResponseDetail;
    Header: Starter.EligibilityResponseResponseHeader;
    Meta?: Starter.EligibilityResponseResponseMeta;
}
