/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EligibilityResponseResponseDetailReferencesItemRefQual = "IG" | "NQ" | "EA";
export const EligibilityResponseResponseDetailReferencesItemRefQual = {
    Ig: "IG",
    Nq: "NQ",
    Ea: "EA",
} as const;
