/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EligibilityResponseResponseMetaSettings {
    favorite?: string;
    imported?: string;
    readunread?: string;
}
