/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EligibilityResponseResponseDetailPlanEligibilitysItemMedicarePart = "A" | "B" | "C";
export const EligibilityResponseResponseDetailPlanEligibilitysItemMedicarePart = {
    A: "A",
    B: "B",
    C: "C",
} as const;
