/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Starter from "../../../../index";

/**
 * @example
 *     {
 *         Detail: {
 *             ResponsibleReportingEntity: "ResponsibleReportingEntity",
 *             Subscriber: {
 *                 Birthdate: "2024-01-15T09:30:00Z",
 *                 FirstName: "FirstName",
 *                 Gender: "M",
 *                 LastName: "LastName",
 *                 MedicareIDMember’s Medicare ID (HICN or MBI): "MedicareIDMember\u2019s Medicare ID (HICN or MBI)"
 *             }
 *         },
 *         Header: {}
 *     }
 */
export interface EligibilityInquiryRequest {
    Detail: Starter.EligibilityInquiryRequestDetail;
    Header: Starter.EligibilityInquiryRequestHeader;
    Meta?: Starter.EligibilityInquiryRequestMeta;
}
