/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { EligibilityInquiry } from "./api/resources/eligibilityInquiry/client/Client";
import { EligibilityResponse } from "./api/resources/eligibilityResponse/client/Client";

export declare namespace StarterClient {
    export interface Options {
        environment?: core.Supplier<environments.StarterEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class StarterClient {
    protected _eligibilityInquiry: EligibilityInquiry | undefined;
    protected _eligibilityResponse: EligibilityResponse | undefined;

    constructor(protected readonly _options: StarterClient.Options) {}

    public get eligibilityInquiry(): EligibilityInquiry {
        return (this._eligibilityInquiry ??= new EligibilityInquiry(this._options));
    }

    public get eligibilityResponse(): EligibilityResponse {
        return (this._eligibilityResponse ??= new EligibilityResponse(this._options));
    }
}
