/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const StarterEnvironment = {
    Default: "http://dev.jasperedi.services:8077/rest/v0/cms",
} as const;

export type StarterEnvironment = typeof StarterEnvironment.Default;
