/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Starter from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace EligibilityResponse {
    export interface Options {
        environment?: core.Supplier<environments.StarterEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class EligibilityResponse {
    constructor(protected readonly _options: EligibilityResponse.Options) {}

    /**
     * @param {EligibilityResponse.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Starter.BadRequestError}
     * @throws {@link Starter.UnauthorizedError}
     * @throws {@link Starter.NotFoundError}
     * @throws {@link Starter.ContentTooLargeError}
     * @throws {@link Starter.InternalServerError}
     * @throws {@link Starter.ServiceUnavailableError}
     *
     * @example
     *     await client.eligibilityResponse.getDocumentById()
     */
    public async getDocumentById(
        requestOptions?: EligibilityResponse.RequestOptions,
    ): Promise<Starter.EligibilityResponseResponse> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.StarterEnvironment.Default,
                "EligibilityResponse",
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "startersdk",
                "X-Fern-SDK-Version": "0.0.7",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return _response.body as Starter.EligibilityResponseResponse;
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Starter.BadRequestError(_response.error.body as string);
                case 401:
                    throw new Starter.UnauthorizedError(_response.error.body as string);
                case 404:
                    throw new Starter.NotFoundError(_response.error.body as string);
                case 413:
                    throw new Starter.ContentTooLargeError(_response.error.body as string);
                case 500:
                    throw new Starter.InternalServerError(_response.error.body as string);
                case 503:
                    throw new Starter.ServiceUnavailableError(_response.error.body as string);
                default:
                    throw new errors.StarterError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.StarterError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.StarterTimeoutError("Timeout exceeded when calling GET /EligibilityResponse.");
            case "unknown":
                throw new errors.StarterError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-API-Key": apiKeyValue };
    }
}
